apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:f3VgujsvqXRMNIJDip3/2RdIOAJk5Cey,iv:UIhNXqDMRghZ5P3PRLiNpWHL+elCddsxPPkO4J7YFaM=,tag:XUk9HMCpuq94PYsn+/wj2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjZNQW1obU1ZOGlFemRH
            M0l2bzVueWhveUgrWUFnRFZ3LzNGVVMrZkNzCmhiUDBkSktvUWROVjNYRWtTdS9V
            R0o3RTBQQ2NUUEczem05UUtKams5d1kKLS0tIC9QVkFrQUhOU3Ywb1BaTEVyRjg0
            aWZwYUZIKzRjK2FGNExRLzdTV0srZGMK/CzbrxLHiFcPI51XKisWJlQfrkq+ngrJ
            gXFjmpLB9JvGtiAPUAYBzgttJI4twuCT5+CAAwvq/WMqF/z/YDx2Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T11:40:02Z"
    mac: ENC[AES256_GCM,data:Hbac6ud5lyZOelF3nq8rEhw3QWGDH/rKaoKfMceLSsvwWHYsxL6zx+nCj2/AYMJ90P201ruVXucn4z40l05AVS35dM2Ylo1PbUtAHmsNGmLTlZlRWoVSBn2/wFg2iv11rUCe8Efxhz19VXgq+J5VM0VXhPmgpaIfCdQvUKoUKUc=,iv:DLYQc5VFiLZ3Wpt/crTfEfqCqptKQoQJeRrgV9q0rhI=,tag:O/OLojA5g+0QDb9/IT+TkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
