apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:h+4ruZ//MuUuHSCn8/wHEGKAGTkZ4zwI,iv:dVdnxbN7Oo1h5d194/K2TqYJVQKl6aXxucrymWR6dVc=,tag:f9vJbRcAIBnIINzmps47kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdkRBS24veTZOcXdod0No
            V2gvdDA2Y25vYkt1bmh0d2tva0laZEVxeG5FClF3RDVHRURRa2VobU9oNWRoYzFV
            ZUc0cFpqN294cTNFL09YeWtvWjJMWWsKLS0tIG94aU9xRFZvcGtSN3E5bENob2k4
            cjRhY1pSYWpFelF0T0ptREdNMDI0L2cK/KzflN4/nPa0LbAWeKiuCKqCbs7C6DsM
            fVh5h5q7aiWmW/XJXvtJuFx4fGw/Fw/JpkN0TKflu5kMh5yHMmsyHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T19:32:07Z"
    mac: ENC[AES256_GCM,data:5Cb6XSgVHWL8lUQPmlcqJs1vaQUfRL5oTGEBjIQV63sKfVvhhvrZdR6p/HWu4GNYGeMK95K8FycuSzYlp97n1GabRUbaQ9d5cpNxJnV26khpbeJADBoQYWhuhEBaN2U7jKDh2nQgBaTGwSPhDSEjAFhot/I47ofW/lNBapBeTw0=,iv:43qfAvbTqV1GdC+gX9c6v74QYNgyDT8xtUk5t3iuF5o=,tag:ITVMYH1sYZm0Uu5nwW4VmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
