apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SSYm2kTkMhDnZjie6EuXYxUZENBqpBle,iv:MGhh74KqOxXPyiarMIqdIwqrK1pp1cen9AxrTluvJiw=,tag:n7SCof9UZp834L88xZMWTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Mml2anZJTFlrS2JCQTJz
            Q1dkK0FiQ2pydXZZcnA5a3dBQ2Q5R0ZEckJZCi9xQWxSSlh6K3RiU1FXTmNsK1F3
            SG5KcW9hL1BRanNUbmxQenhoYnVmaHcKLS0tIFNtekkyRi82bFVkcGFncDBxbFRL
            N1NXdzFGRE95cjR0azRSZ1NQUGtlOVEK/WrxucFlnoUDuzZRaRXpCNE1oJKGLrry
            UCoVUkstX0kyN+Au+rc9UxlCkJoWy7KL3HMI+WDZ0+EWXoU+4bijJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T07:19:26Z"
    mac: ENC[AES256_GCM,data:N5oQ0mHvjqhQ3+TeEhIOQz4FQdzlkc0Nzd6c52gVReW6/CRqLlPKYfQZTf1BEn/Rpp0TlnMT6ieOQLAapkOJawaX4Ue6wvxP3Kf3ZQK4j3rJICh5W1OZHftIusDhEJPVmkZmIM6qaCj17w8havEP5z4HTCShCiCqJ+OgaluSuNg=,iv:AeSKxaU4wzpb0hj7lBpfNYNmO+RcWW3DaPsqmudbpAs=,tag:2MLdVfJBqG0dLLHR7alHPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
