apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:iQbEykPf3cu/p26PJWXPPWmAjHaWaGmXyNC9y9uxTUfYkW6tkibYIA==,iv:HFzg4xbl6yCpjZMKhy0UdroB4KD+VSGZcjF/+Vx+m3I=,tag:mPlap6ieboH2+w00ANUJ+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdlpwUDZORk1UNTZHQVZF
            YWpLaDMvNGlaWG52QVVDZzhXaEtxUTdGTGprCkdQY1lWZzlCTW5HUFhDTXNLVnBp
            OUNxdVhYMW10bHdobWd1aXk1bDlUK1EKLS0tIGgwelJ4VnQzcEtMa0hKeXV6K0lR
            bFBWODJndUFVQWx2ZjBZYWFSck5CUWcKEGPIbnM3aaSJdwAap+GNQprzhFhxMBwv
            Mlw9wSpaDyMiUVGRzho9La6msOIXBCskzZUyVdKQrKQ+Z/Nrf0kKyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T11:40:02Z"
    mac: ENC[AES256_GCM,data:Vhpy8TuxBHnjhhhwfv7YZtBm6ukRFk31qPbsrID+byhUw6ksVRuEfgjzdF9OecM38bpH/mKQksYHHKSXold9u15FSozLDGnbvQkJ97KhLeOLY5EnReoOqxHSCqGe6TPtj7ERq6PFwh2LukpEfLbrKBfaDMZz6heBpQo13cqQLK0=,iv:I9hheJgon/kiwoPZ3Pxvm+3xtguXNnL5cGHPn+u/1f8=,tag:C3ZjtcCpK3VzqtIvFf4M9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
