apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:lsxHX9xI7OykIb2cFCQ1dR+1ZRE0A1fvnIp/wmOPeQLwc/LhJ7eL6Q==,iv:p2zvUdgghlHYzUI0wm+6vYrlf91tdvuvcqNBQjfVszw=,tag:d/6c+d7i643LK4L4aVn5EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNktlekdlb0p6UXdOeXJU
            VzRGRHl3T2o4NUU3NytIcFBvSXl1RXRVR0I4ClVKYTF6RSt2WTI4bHdjWVhCTWdL
            dGJVd2ViUnVmdGVoTWgrMzdtMnFHT0EKLS0tIDVGajZDZi9sZUJ3Y0xnVHdaMkVB
            RXlieWFSbnh3NUlzVUZhQmo2TlNsOTgK1sM4A26+m/sz/VTHLposxSK9004U73rn
            1ljA6joOn7TGcxRB/NnpDQ07u/ctXqsvTTd66B/3rtDFJCDWuTUzWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T07:19:26Z"
    mac: ENC[AES256_GCM,data:SmnELcLdo/CULtDc5yFwgLuYCdzrKPF0J/z7p0S+ZiIhvr578CQbDvFet43n3YVHWG3gl/37S72tSuRhPYzhWIDK0a0PMbPDA0Ep6MwcBwnhEW7Vf/Sf8+PWpV8INgzbV1iPs5oj9hvSM3+AZP0PeqfKxwOh+wrcOa9J1xwGMbM=,iv:nvrxdwOmoxkSHcCYBH2YamXZLfqkNnYCJzTzVysFKMI=,tag:QvsA8mT/njC2DM9nuD/6EA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
