apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:glHqb9TaG5CM8uHRzr6lWa0/KnS7QCvARRca9GQXdHkdJ7sPQfLoBQ==,iv:koaPnDk2RduKY52bpRo3HvKQNwnuZh0TvZ9CMkMgmW8=,tag:LCQr2zYrdlzdy34TNCfONQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dEdiZ1ZuL09qMmUydzZX
            TGZUNDVXMWJMTzkrY0hSQlFBR3RVYjF6T1RZCjZJb25jb0hkQ2drdTFVdFVJV2gx
            dE9PTVl2cm1YY2JVWURZeUQrUnFGdGsKLS0tIFYwNDROSHZYL2FQK1hpRXcvSXE0
            QUdrUTI0TG10UUlJVGk0UWtKTGlTMFUKiOSMKvlNOdwzSMprQs+QM6AlE3NzE8Bm
            YgJWJCM63NT9k5+EWf58S4RfsOuozkMGIf1+5L2IQXscd65JGZqKIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T19:32:07Z"
    mac: ENC[AES256_GCM,data:m84Wvl0d1ZC5rcZeKiM3o82IePManTWA9TzU32MEgrY8noSTMGLN+KLuRePRdZ/AkPa4dOLJaJozkDZ/cKwdsw9fsEKyKHpTY6olWKQSQpZW2g6GwkRWo0SEd6A4LsqzsuUEl8070oyoxmYMZLccqjHnk7sNP09ivO8uoOgOUnM=,iv:W2Pet5a+E1GfZ0vHD+mFUjr+a5VhsichX1nYIxBqEYk=,tag:F0TeIQYQspHHqnXPQ8Ef4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
