apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:xPdIalDWcU5hqJj+i8Rh+bmduwmLw74zZkmFyeNQ+w0RM3AyxqJglg==,iv:gb593JcUoEtb1CpsSSTdcLLhklY8WdKnqPc4BPBG1I0=,tag:LI44cBFklW1knUC3Aa11kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRmhQdTZHNmhOd0FVQVZs
            bDlXQ0dmS0dtL2RzejJvSHJFTzdoRStISFVBCmNpRmxoS1ByMnA2TXc0bkc2MTcy
            SFFVWDhWOWlSNFNWYVU2QUxZMkNyQkUKLS0tIDhRUEpNemUxVzIrTDg5dXBUeWdw
            dEpRT0lvcFpWQ2ZldSs3dXRqdll3UFEKlv7vN11dAgyLxWXnkq2zESBut1chyHIB
            V3+CrnlS/+zCVhcbzhjr3hFZ5wzZciNBAc/476GbSjSsnSbhdsd9qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T11:40:02Z"
    mac: ENC[AES256_GCM,data:pTIpatrEy1ntpfFV1QFwx8VR91W0xlefB0xi0+aQEHO5PR7VRK0G7AANDQLMDjLmOyx9Obz52ARjwQHUBPZgqrfl2AsOkGUeqA+gpTvLOr2WQi8+RX5o/Iql39fvR7Zrv3CbAjqwuE1wo9RWDXcsKuAnXs9Y6Wsc9Z9yxpsGLuY=,iv:nRC9SMoIz8MJxjNMgJzjHk2Ci55l8bUDGl/8x2JJSsE=,tag:gt28Ocz/bFvV9GH6yWs3TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
