apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:DQr0q/7PXOtKI67OqcU67NEBIB+r43L4zgNlYdxl4RG1lGgax+aimw==,iv:PvEQnZwKCczBdwdQ+U+X9VZSulIA41peVByMBccxAoY=,tag:ZH3fRbhCwULjHHnEEkbKUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQ0dzdE91bUVoQ1dNRmtN
            V2pOVkJhQU50MXNudXNGOHBsdlRKT0Y0ZjFZCk9yekpCQkg0MlFRS1VCZ3EzeWFi
            dEZURWNSN1NHYWlIeWk4N1JZUWR0eFkKLS0tIFc1NzVTMzhmWGpValhKenhraHVz
            V2xOSEpZNnJLL1IyVjNpUFZkL3ptNnMKgabqdDpM6W5og48b0c5KcfgMnFc9Lvh1
            D/P4woeMiDRYbLDCM2hylC2jibpCWE3riuy54VPLFcMdtk6hwDxONA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T07:19:26Z"
    mac: ENC[AES256_GCM,data:p26K8/l7m9iC/gIIhQVwoQ+G/NXmGNNbPmIdkSyHJ60nGkGN3o03pAU2lfRTKaHBrLXPER1448Slt+N8t4lCnHAroJBESmXqtANe0/6MJSh9w9gdgBcGR7SAHy4o27h7eFvAFiXGQayHX5BVsnpBkmqDe97dcQ1ftT+rnwMpdE4=,iv:rFlfskMo1znp/jMcKfRvbahS4dvxfTZgoIhBrBJQ17Y=,tag:f8EGoquSsJTgGS43tLMJCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
