apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:FjT3aIeaY2k+hPplRtTaOQOOlza0fcLAsHvoCdh7QOKUrJD4fvhwqA==,iv:tqai1bVpfPZzIQULEt8gLUFbvqKtMYmcl7m/vghK5nw=,tag:x4QJ/BhZ6zwZwPHPOs4DEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWlBHS0U0TEkrRGtlMGow
            MXJESk9KYzQ2bVR0L2pyMFhGVGdEZ3JvYWpJCnMwWEZRL1gwcDd2SUNDTURpQ2xa
            a3YzUFZRakQyWG50SFFGT1plWmwvTDgKLS0tIHBheFU0bUt3MnJWZHFVbmNjRUdJ
            VUp4aHRFcVdnZFkzb2REWjBBSGxhMjAKRDAUdPewQ8N4OTJ2zTwrcARbDlLn6Cu/
            qJwumdcQdxvP4YMePARI0cG0omT+99hd79oyykf3vWCioDYLVHFoAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T19:32:07Z"
    mac: ENC[AES256_GCM,data:r+WeODOxeQKeMIpD3WxpUXCCTKUEzJzJpWeBy4PfSfao8znJQP7gHgFxpSYtzd6qAk2iKZZSh+V5JrnNItDew2DIMy8zogpszHvENr+A1Q06J51NXSY5zS2JPeTm2pyZuijflFY6pE+HbGZdFGIFJzJ661aWmoQJTP5GgmJHwN4=,iv:ArNovy/b0UuLFxTccjTKxJuFkGdjpJvALwAHC/n22Tk=,tag:QINmTNRn33C7Fqe9L/e5Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
