apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:E0CYZ4lmp+mL0sXd,iv:Z8skxB7Qpx/gGVBa3BLeqUmQCnDeiaA7mBKcHzlmABo=,tag:xf6NdhO6uz8dHTn8ZAg9wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Y3dQbEhYWjBzSTNLSHdR
            cWZRaTB1Y2dwL3RKRXhkUURiVCt3b1hqUkhJCmFKVDRmL3ZxekoxaWx4aldOeVk5
            MUVNOWQ4YW16UWlSbEo5cTduWVN4dGMKLS0tIFpCOFFndXBqbVFSUlpuRlh0TURq
            REdIR2ROWndTelR4WGNxa1ZORGgycjAKlUWu2TBlvEC+LL5AuwQgeUxmXnvpoDeT
            3pGkFVJX7Ec9D5XkSKfFx4CrpLi8oFztTmlGNgyD3SU7hjKppeyoPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T07:19:25Z"
    mac: ENC[AES256_GCM,data:fqohYeAKeeluZ6s/JHGviYSoQmcQuxZzeZsmfr4Jr//jXmmFPQzo13Hx6Ln86TDYK3NfkGWC5u3BETEptdq8K01FUK44IsgqvxGS60UZ5wN0PLXK/JjjEV+GgvPdc5vCCZfMyueSCzhugUazDrohIRpJ+7LJX858ygzuLd4soSM=,iv:I1vGbYDpjP2Rj3xH7F9RwtZH/ovh+LHG/LfrALhvmC4=,tag:YVNWpyBOEVgBTdxjoKmHkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
