apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:rW9hiZsvTE0uoWs/,iv:KuqEuQ926X1pH/eOar4V4XvWsqehzEcSHVnWwMPH8Dc=,tag:7EM3VRm5EYSOlyDG9xI6sQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtY0x5eGNScDJvUnlGeHFF
            cmVSZDYxeGM1Y3lQKzlNRWxXUnEvcVEzV3o4CklWUk1WOFJMNVd1blUreUtYaDd6
            ZmRUbTBxY2dZNFc5RlJ4ZFdBQ0pVbW8KLS0tIFRyZjluaU9NbmtUVWNyL1RGWmVl
            ZWJobzUwa09vWFcydUhvcWxiQmtZNGcK0hk7fFsO3lzHZEgYPTAe5Ak6iTFJWyQ2
            Gn1UpnLjy0phNKjIyvXbjBlphpN5c0G4x49ystxXk5gh24zJzb73KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T19:32:06Z"
    mac: ENC[AES256_GCM,data:MqLGtubjLJEApTPsj6KLTnMQKh4XqYWMC2K524VetEWK8iTmQr9uoLYXZNsKyPf1cEBJxI6kfSc4hrrZ+W7FsBook5mUOjJX8Mej1tSob+xyCrE92/B3QHZAModrOdPQUl1Cl3ZFzX7E7DzJ8+3YPJ/gHfqkbFbdWm7noEWxFvE=,iv:dOPCo8osy/KwzunsgqKGLkJ6bTtiyZc0KSZTZCjREVc=,tag:/FDl2uzr6wRQKHM2ZoHu6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
