apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RbPfcfRqla1jlg7hl3jur/Nnyg==,iv:tIWBeaMScoEk1GRPEFK8C/1FSwLOVLbZPG8IBqJCYhU=,tag:MUO13QpqAfZeCUnvqgRaiA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7AQ+tWUk0lQ=,iv:gn+/ttxtblQfYYoeNtvsP8vbwSm6Vi0gDX6+TuLkQ0c=,tag:eHtdaF6GsR+q3SwxhvslMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVEdJQVZLM0ZkRkIybTFm
            UFIxVWFXODFCNlZXcEtuZkRCQU90V2Nld0dJCjl5RXFMOXplcE9Pcm54cVN2ekt0
            RUpTb0tPQTBiSllVSk9XOUJOQjZHMGsKLS0tICs1MjNFWGZaSG1MUFRIajNhMlFs
            WE10TTVlb2dkSXR5OERKeHBzZ0RuK2sKNT8pbxAS+d0rH26RU7cMOBbbtNvKJ4JV
            juOquLh6/D6gNrbkxY3xSu/B7AiDNl/DtH0JRkAcEgJye7IOm3nMcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T11:40:01Z"
    mac: ENC[AES256_GCM,data:ddgXA+WV6YIvWkTNcwZZA/ZwdyXZBGs8lkwxz8SpZ340heeKU5x+9nLT1Ev+WOHIU436PLk6slhUnVKqGWhzDPS/GDQ7d7hDYH6ZINt0kMZ9yYDkp0Vnz0XK6AIr8u8AAhFJL3G/1IjmkNnhuGdG1xKLlX8AR8a0ad0ctBfWrT8=,iv:JNgjI2Y9QUGt15U6Wfpg5FisiKI1Yjwk2FNqySsgCCs=,tag:xSp8pVytwEk+djxEyD1G5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
