apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Op6kEAUL5GOES0E+,iv:LsRkdhbMovkWF6HjDAeHvjnAwFpNIUYGoQOsaLIj4ys=,tag:zmgyAqxuWFglUEn3q+sV/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUemVlVEpkR3paZTJDMisw
            a2xFRzhmb2RQSCszMnJqb0JNNWhTL1hpWHpVCk5Dd3VyUWJMWERIRWM0TUc1YXcv
            OS84dlYxOVFaN0lGRi9IcStESmhkeXMKLS0tIDhwbHdORzMvNVpIUEpiNW9heWNr
            R29hTDZ6Snh4VTV1SThuRklRQmdvalEKotwO9ZAtgtqhkLvZUpza+U9BPfe+ykmJ
            0KeRF7XS5TRcl0sY1gRceBG65D5Q2Zk/2o5vqdL4/bwo4R9LmFqH3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T11:40:01Z"
    mac: ENC[AES256_GCM,data:WWADFDsrhLckVSNxxDBDqvmawv6Q6cpA3kFwFo2EkPVXataxCQ7DTa5a8fXEAlbo8Ux1onkcK05xaG/49dkQ/fwXQz5YSOLLBVa0JYBihBbUAFJiGjcLC0GzLvzhdDLJrNKLTy+FmB66GHhQkK/YAYI698zdfNi0OibNQAWaA6U=,iv:LkcsOWy5NxOhgqik1szmr84pnyHTtNNDFNOF7YtXcZE=,tag:yoUbDWMd/AoGvR8ak4/PeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
