apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ee6x6wQxyznjdsYRR/y3RPU8pg==,iv:BWvnt5UHRF+AmERBeNOtGPJ/0dNujmhEaCOpBMemMBk=,tag:uOcaxzaNUjA0bUdY4g6V9w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:2GtIF5a4lLw=,iv:lI1xaCHSYp6c8TXSGrteXiQJN1HZjzubPOt1jOuEfNA=,tag:XJn/ISXuH+no+bq549Olkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTzQ4L0hBL3ljMlJzNzcx
            VG10QXNWV3YzQzljNEhUQU54dGQ3Qnl1SkVNCkd1RnFWQzBYZ2JpZEtzeG53MGpR
            UGl6NUE1bE03Z3pjeStpUFRwaElXZncKLS0tIFIzYTRUTUw4M3M2U3I1bEhwbk4w
            YUdXdUx1ZU9ZV0tBdU1ZVTBIaUtMSE0KsbmtFw+ahgEoYicYOK2TK5yhoUvvFcLu
            Yl42xBNHxA5iRQGW0Ysn2JLZUmWVHPXPqan68eUoBFl21WjY3mbBFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T19:32:07Z"
    mac: ENC[AES256_GCM,data:8Tc4QG6OQAYDbnYGKqSvjXkaX0sjMITlwe/nxjDT2GyWjYvU7Nb8yy9sRpu0kkEUksyNRv9bqq4cep0RYW/DG4f8WYJSf4KGncQaeM5gQpMyS9SAFDahBap2dt0o4JDoevF9Dk79KRJK/0IShdurAkrDRF2iFeCgFBQjOCeR+wM=,iv:OP9K3fPaa3SdwtVdDEQd9XZ6Fg+zn+ewC2vtdBR02UI=,tag:WuI1ShWw5lM+ey7JNsFRhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
