apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:aYPeO4z6udElQjyS9cqwTT5gaw==,iv:ncpqjMfeo24k061FzIkkx6Fi92Ksf49VxfOPfOhH3rE=,tag:gkFORIKJyUoFtWSqgvbvDQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kJWhnphnNbk=,iv:Kiv3OIJAGr2gbc+JWcK3+RtBEryyKdBmA5XI4yq0ehA=,tag:PNICeyPFXfhTtR8i5/BgZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ptththqpxnx0zuzmq0peq9x30vqgdedjsdlsuzxr5gfc36mnwqlsylrpr8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZUdsMVNma2MxUGhpRzJB
            bktSU1puY1VDTmNCUGgvTG1iSmFQMURHQ1RzCmN4ME5DWnQxNWFWL1o5dndpMHlF
            Z3AyN1pBbm1PRUNsdzJkU0NXaitKWDQKLS0tIGNGRU01RGZNV1F0d2YrOVI5N0NG
            aGphN0FoZXdvYkU0VkZudHdzUWc2ZEUKyp1f9PpRynhO9U0sqGkCCaqRM/v5fXqp
            jEHrNu71xTEbVDeSkWqc+maIGQAZ5FSbKybWy7IPRH9C0NcUofEt1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T07:19:25Z"
    mac: ENC[AES256_GCM,data:6FNU4kaNWFGauA0MhYJBTuzeQThm9VghaIzKBZKXKPkQJG8bOBcnQ/6Jns64ckfUeigGzZ/fRiQkSB129fFhENe4AD3nLsYqWYE6wV7AKIrwPlQKiSqNEnUo/CtUJ8E1AcJK21xOTMOJDbu/KZobsQ3RFY1BtRUzyFev+UEcPrg=,iv:k2WEOOUG0HR9OIMETSnGyma7nwvM9APZaagL+2Ff5zo=,tag:UF0UZZsmolYCBdwsIjc9WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
